# SPDX-FileCopyrightText: 2026 Florian Mücke
# SPDX-License-Identifier: GPL-3.0-or-later

name: build

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Build and test
        shell: pwsh
        run: ./build.ps1

      - uses: actions/upload-artifact@v4
        with:
          name: network-sandbox
          path: out/network-sandbox.exe
          if-no-files-found: error
